# Generated by Django 4.0.3 on 2022-03-25 13:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ImageField(upload_to='')),
                ('street', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[(app.models.StatesEnum['NSW'], 'New South Wales'), (app.models.StatesEnum['VIC'], 'Victoria'), (app.models.StatesEnum['QLD'], 'Queensland'), (app.models.StatesEnum['SA'], 'South Australia'), (app.models.StatesEnum['WA'], 'Western Australia'), (app.models.StatesEnum['TAS'], 'Tasmania'), (app.models.StatesEnum['NT'], 'Northern Territory'), (app.models.StatesEnum['ACT'], 'Australian Capital Territory')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
