# Generated by Django 4.0.3 on 2022-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('New South Wales', 'NSW'), ('Victoria', 'VIC'), ('Queensland', 'QLD'), ('South Australia', 'SA'), ('Western Australia', 'WA'), ('Tasmania', 'TAS'), ('Northern Territory', 'NT'), ('Australian Capital Territory', 'ACT')], default=None, max_length=100),
        ),
    ]
