# Generated by Django 4.0.3 on 2022-03-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[(1, 'NSW'), (2, 'VIC'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT'), (8, 'ACT')], default=None, max_length=100),
        ),
    ]
