# Generated by Django 4.0.3 on 2022-03-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('NSW', 1), ('VIC', 2), ('QLD', 3), ('SA', 4), ('WA', 5), ('TAS', 6), ('NT', 7), ('ACT', 8)], default=None, max_length=100),
        ),
    ]
